# Generated by Django 5.1.6 on 2025-03-07 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='courseregistration',
            name='unique_course_registration',
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('session_registration', 'course')},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='ca_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdata.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course_registration_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='session_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='appdata.sessionregistration'),
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='score',
        ),
    ]
