# Generated by Django 5.1.6 on 2025-03-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionregistration",
            old_name="session_registration",
            new_name="session_registration_id",
        ),
    ]
